return {
        ["Lighting"] = {
		[1] = "Ambient",
		[2] = "Brightness",
		[3] = "ColorShift_Bottom",
		[4] = "ColorShift_Top",
		[5] = "EnvironmentDiffuseScale",
		[6] = "EnvironmentSpecularScale",
		[7] = "GlobalShadows",
		[8] = "OutdoorAmbient",
		[9] = "ShadowSoftness",
		[10] = "ClockTime",
		[11] = "GeographicLatitude",
		[12] = "ExposureCompensation",
		[13] = "FogColor",
		[14] = "FogEnd",
		[15] = "FogStart"
	},
	
	["BlurEffect"] = {
		[1] = "Name",
		[2] = "Enabled",
		[3] = "Size"
	},
	
	["SunRaysEffect"] = {
		[1] = "Name",
		[2] = "Enabled",
		[3] = "Intensity",
		[4] = "Spread"
	},
	
	["DepthOfFieldEffect"] = {
		[1] = "Name",
		[2] = "Enabled",
		[3] = "FarIntensity",
		[4] = "FocusDistance",
		[5] = "InFocusRadius",
		[6] = "NearIntensity"
	},
	
	["ColorCorrectionEffect"] = {
		[1] = "Name",
		[2] = "Enabled",
		[3] = "Brightness",
		[4] = "Contrast",
		[5] = "Saturation",
		[6] = "TintColor"
	},
	
	["Atmosphere"] = {
		[1] = "Name",
		[2] = "Density",
		[3] = "Offset",
		[4] = "Color",
		[5] = "Decay",
		[6] = "Glare",
		[7] = "Haze"
	},
	
	["BloomEffect"] = {
		[1] = "Name",
		[2] = "Enabled",
		[3] = "Intensity",
		[4] = "Size",
		[5] = "Threshold"
	},
	
	["Sky"] = {
		[1] = "Name",
		[2] = "CelestialBodiesShown",
		[3] = "MoonAngularSize",
		[4] = "MoonTextureId",
		[5] = "SkyboxBk",
		[6] = "SkyboxDn",
		[7] = "SkyboxFt",
		[8] = "SkyboxLf",
		[9] = "SkyboxRt",
		[10] = "SkyboxUp",
		[11] = "StarCount",
		[12] = "SunAngularSize",
		[13] = "SunTextureId"
	},
	
	["ColorGradingEffect"] = {
		[1] = "Name",
		[2] = "Enabled",
		[3] = "TonemapperPreset"
	},
	
	["Clouds"] = {
		[1] = "Name",
		[2] = "Enabled",
		[3] = "Cover",
		[4] = "Density",
		[5] = "Color"
	}
}
